### PR TITLE
Add registry value to kube-event-exporter doc

### PR DESCRIPTION
**Pull request by ivankovnatsky**

### CODE REVIEW

**Review by georgethegreatat — APPROVED** [review]
LGTM

**Comment by georgethegreatat** [comment]
@DanyloSafankov please validate the commit and apply if ok.

**Comment by illshestopalov** [comment]
@georgethegreatat LGTM

**Comment by georgethegreatat** [comment]
Approved

**Comment by DanyloSafankov** [comment]
@georgethegreatat LGTM

**Pull request merged**
